<a href="https://colab.research.google.com/github/fridymandita/KCBV/blob/main/Struktur_Data_Dasar_Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Deklarasi Array
numbers = [1, 5, 9, 4, 100, 0, 7, 8, 9, 10000]
numbers


[1, 5, 9, 4, 100, 0, 7, 8, 9, 10000]

In [ ]:
numbers = list(range(10))
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
mixed = ['a', 1, 2.0, [13], {}, -100]
mixed

['a', 1, 2.0, [13], {}, -100]

In [ ]:
#Contoh Array 1D
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
#Contoh Array 2D
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Contoh Array Multi Dimensi
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 2, 1], [6, 5, 4]], [[10, 11, 12], [12, 11, 10]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 3  2  1]
  [ 6  5  4]]

 [[10 11 12]
  [12 11 10]]]


In [ ]:
#Cek Dimensi Array
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
#e = np.array([[[1, 2, 3], [4, 5, 6]], [[3, 2, 1], [6, 5, 4]],[[10, 11, 12], [12, 11, 10]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
#print(e.ndim)

0
1
2
3
